from src.modules.audit_logs import models as _audit_logs  # noqa: F401
from src.modules.auth import models as _auth  # noqa: F401
from src.modules.catalog import models as _catalog  # noqa: F401
from src.modules.codes import models as _codes  # noqa: F401
from src.modules.customer_payments import models as _customer_payments  # noqa: F401
from src.modules.customers import models as _customers  # noqa: F401
from src.modules.document_numbers import models as _document_numbers  # noqa: F401
from src.modules.employees import models as _employees  # noqa: F401
from src.modules.inventory import models as _inventory  # noqa: F401
from src.modules.location_assignments import models as _location_assignments  # noqa: F401
from src.modules.locations import models as _locations  # noqa: F401
from src.modules.pos_checkouts import models as _pos_checkouts  # noqa: F401
from src.modules.price_levels import models as _price_levels  # noqa: F401
from src.modules.price_rules import models as _price_rules  # noqa: F401
from src.modules.product_categories import models as _product_categories  # noqa: F401
from src.modules.purchase_invoices import models as _purchase_invoices  # noqa: F401
from src.modules.rbac import models as _rbac  # noqa: F401
from src.modules.repack_orders import models as _repack_orders  # noqa: F401
from src.modules.sales_invoices import models as _sales_invoices  # noqa: F401
from src.modules.stock_adjustments import models as _stock_adjustments  # noqa: F401
from src.modules.stock_counts import models as _stock_counts  # noqa: F401
from src.modules.stock_transfers import models as _stock_transfers  # noqa: F401
from src.modules.supplier_payments import models as _supplier_payments  # noqa: F401
from src.modules.suppliers import models as _suppliers  # noqa: F401
from src.modules.tenants import models as _tenants  # noqa: F401
from src.modules.units import models as _units  # noqa: F401
from src.modules.users import models as _users  # noqa: F401
